In [1]:
# Libraries

import os 
import pandas as pd
import numpy as np

## Prepare OriginalData.csv for reformat

In [2]:
# Read original data import

original_data_import = pd.read_csv('../../data/OriginalData.csv')

display(original_data_import.head())

dataframe = original_data_import

# 'original_data_import' is intended to be READY-ONLY
# From this point on, morph dataset using 'dataframe'

,Dates,symbol,PX_LAST,Dividend_Per_Share,TOTAL_EQUITY,CUR_MKT_CAP,gics_sector_name,gics_sub_industry_name,gics_industry_name,gics_industry_group_name,...,NUM_CEOS_EQUIV_INC_COMP_PD,CEO_TENURE_AS_OF_FY_END,TOT_COMP_AW_TO_CFO_EQUIV,TOT_COMP_AW_TO_COO_EQUIV,TOTAL_BOD_COMPENSATION_AWARDED,TOTAL_BOD_FEES_PAID_IN_CASH,TOTAL_BOD_STOCK_AWARDS_GIVEN,NUMBER_OF_BOD_CHANGES_DURING_FY,DATE_OF_LAST_BOD_CHANGE,NUM_DIR_INC_IN_CMPNSTN_PD
0,2014-04-11,AAPL,18.5580,0.1089,120179.000,463486.4114,Information Technology,"Technology Hardware, Storage & Peripherals","Technology Hardware, Storage & Peripherals",Technology Hardware & Equipment,...,1,3.7500,18520521.0,0,2638340.0,697500.0,1906645.0,2,2014-07-17,8
1,2014-04-11,AMT,80.5500,0.3200,3701.605,31870.1921,Real Estate,Telecom Tower REITs,Specialized REITs,Equity Real Estate Investment Trusts (REITs),...,1,11.2500,4904866.0,0,1975088.0,775000.0,600071.0,1,2014-12-18,9
2,2014-04-11,AMZN,15.5870,0.0000,10328.000,143440.4076,Consumer Discretionary,Broadline Retail,Broadline Retail,Consumer Discretionary Distribution & Retail,...,1,18.6670,5962307.0,0,797000.0,0.0,797000.0,1,2014-07-31,9
3,2014-04-11,BHP,58.8727,0.0000,82279.000,180544.3056,Materials,Diversified Metals & Mining,Metals & Mining,Materials,...,1,1.1667,4639000.0,0,4695000.0,3617000.0,0.0,1,2014-04-15,13
4,2014-04-11,CAT,101.4500,0.6000,20369.000,64707.0750,Industrials,Construction Machinery & Heavy Transportation ...,Machinery,Capital Goods,...,1,4.5000,5286968.0,0,3206983.0,1714174.0,1375110.0,1,2014-12-31,11

In [3]:
# Index by Date column, drop Date column as feature 

# First, cast Dates to datetime format
dataframe['Dates'] = pd.to_datetime(dataframe['Dates'])

date_index_dataframe = dataframe.set_index('Dates')

# 'date_index_dataframe' now indexes by what was originally the Date column
date_index_dataframe.head()

,symbol,PX_LAST,Dividend_Per_Share,TOTAL_EQUITY,CUR_MKT_CAP,gics_sector_name,gics_sub_industry_name,gics_industry_name,gics_industry_group_name,gics_industry,...,NUM_CEOS_EQUIV_INC_COMP_PD,CEO_TENURE_AS_OF_FY_END,TOT_COMP_AW_TO_CFO_EQUIV,TOT_COMP_AW_TO_COO_EQUIV,TOTAL_BOD_COMPENSATION_AWARDED,TOTAL_BOD_FEES_PAID_IN_CASH,TOTAL_BOD_STOCK_AWARDS_GIVEN,NUMBER_OF_BOD_CHANGES_DURING_FY,DATE_OF_LAST_BOD_CHANGE,NUM_DIR_INC_IN_CMPNSTN_PD
Dates,,,,,,,,,,,,,,,,,,,,,
2014-04-11,AAPL,18.5580,0.1089,120179.000,463486.4114,Information Technology,"Technology Hardware, Storage & Peripherals","Technology Hardware, Storage & Peripherals",Technology Hardware & Equipment,452020,...,1,3.7500,18520521.0,0,2638340.0,697500.0,1906645.0,2,2014-07-17,8
2014-04-11,AMT,80.5500,0.3200,3701.605,31870.1921,Real Estate,Telecom Tower REITs,Specialized REITs,Equity Real Estate Investment Trusts (REITs),601080,...,1,11.2500,4904866.0,0,1975088.0,775000.0,600071.0,1,2014-12-18,9
2014-04-11,AMZN,15.5870,0.0000,10328.000,143440.4076,Consumer Discretionary,Broadline Retail,Broadline Retail,Consumer Discretionary Distribution & Retail,255030,...,1,18.6670,5962307.0,0,797000.0,0.0,797000.0,1,2014-07-31,9
2014-04-11,BHP,58.8727,0.0000,82279.000,180544.3056,Materials,Diversified Metals & Mining,Metals & Mining,Materials,151040,...,1,1.1667,4639000.0,0,4695000.0,3617000.0,0.0,1,2014-04-15,13
2014-04-11,CAT,101.4500,0.6000,20369.000,64707.0750,Industrials,Construction Machinery & Heavy Transportation ...,Machinery,Capital Goods,201060,...,1,4.5000,5286968.0,0,3206983.0,1714174.0,1375110.0,1,2014-12-31,11

In [4]:
# Cast other dates to datetime format

# Find columns in need of cast
date_index_dataframe.info()
# 1. DATE_OF_LAST_EXECUTIVE_CHANGE
# 2. DATE_OF_LAST_BOD_CHANGE 
 
date_index_dataframe['DATE_OF_LAST_EXECUTIVE_CHANGE'] = pd.to_datetime(date_index_dataframe['DATE_OF_LAST_EXECUTIVE_CHANGE'])
date_index_dataframe['DATE_OF_LAST_BOD_CHANGE'] = pd.to_datetime(date_index_dataframe['DATE_OF_LAST_BOD_CHANGE'])

# Compare to original .info() call for 15748 non-null count for datetime64[ns] on denoted columns
print('\n\n')
date_index_dataframe.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 15748 entries, 2014-04-11 to 2023-12-29
Data columns (total 48 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   symbol                            15748 non-null  object
 1   PX_LAST                           15748 non-null  float64
 2   Dividend_Per_Share                15748 non-null  float64
 3   TOTAL_EQUITY                      15748 non-null  float64
 4   CUR_MKT_CAP                       15748 non-null  float64
 5   gics_sector_name                  15748 non-null  object
 6   gics_sub_industry_name            15748 non-null  object
 7   gics_industry_name                15748 non-null  object
 8   gics_industry_group_name          15748 non-null  object
 9   gics_industry                     15748 non-null  int64
 10  gics_sector                       15748 non-null  int64
 11  Year                              15748 non-null  int64
 12  TOT_COMPENSATION_AW_TO_EXECS      15748 non-null  float64
 13  TOT_SALARIES_BNS_PD_TO_EXECS      15748 non-null  float64
 14  TOT_N_EQTY_INCENT_GIVEN_TO_EXECS  15748 non-null  int64
 15  TOT_SALARIES_PAID_TO_EXECUTIVES   15748 non-null  float64
 16  TOTAL_BONUSES_PAID_TO_EXECUTIVES  15748 non-null  int64
 17  ALL_OTHER_COMP_AW_TO_EXECS        15748 non-null  float64
 18  TOT_STK_AWARDS_GIVEN_TO_EXECS     15748 non-null  float64
 19  TOT_OPTION_AWARDS_GIVEN_TO_EXECS  15748 non-null  int64
 20  T_PEN_NQ_DEF_PEN_GVN_TO_EXECS     15748 non-null  float64
 21  TOT_OTHER_COMP_AW_TO_EXECS        15748 non-null  float64
 22  NUM_EXECUTIVE_CHANGES             15748 non-null  int64
 23  DATE_OF_LAST_EXECUTIVE_CHANGE     15748 non-null  object
 24  NUM_EXECS_INC_IN_COMPENSATION_PD  15748 non-null  int64
 25  CEO_DUALITY                       15748 non-null  int64
 26  TOT_COMP_AW_TO_CEO_EQUIV          15748 non-null  float64
 27  TOT_SAL_BNS_AW_TO_CEO_EQUIV       15748 non-null  float64
 28  TOT_N_EQT_INCENT_GVN_TO_CEO_EQ    15748 non-null  int64
 29  TOT_SALARIES_PAID_TO_CEO_EQUIV    15748 non-null  float64
 30  TOT_BONUSES_PAID_TO_CEO_EQUIV     15748 non-null  int64
 31  ALL_OTHER_COMP_AW_TO_CEO_EQUIV    15748 non-null  float64
 32  TOT_STK_AWD_GIVEN_TO_CEO_EQUIV    15748 non-null  float64
 33  TOT_OPT_AWD_GIVEN_TO_CEO_EQUIV    15748 non-null  int64
 34  T_PEN_NQ_DEF_PEN_GVN_CEO_EQ       15748 non-null  float64
 35  TOT_OTHER_COMP_AW_TO_CEO_EQUIV    15748 non-null  float64
 36  NUM_CEO_EQUIVALENT_CHANGES        15748 non-null  int64
 37  COMP_LKD_LAST_CEO_&_EQUIV_CHG_DT  15748 non-null  int64
 38  NUM_CEOS_EQUIV_INC_COMP_PD        15748 non-null  int64
 39  CEO_TENURE_AS_OF_FY_END           15748 non-null  float64
 40  TOT_COMP_AW_TO_CFO_EQUIV          15748 non-null  float64
 41  TOT_COMP_AW_TO_COO_EQUIV          15748 non-null  int64
 42  TOTAL_BOD_COMPENSATION_AWARDED    15748 non-null  float64
 43  TOTAL_BOD_FEES_PAID_IN_CASH       15748 non-null  float64
 44  TOTAL_BOD_STOCK_AWARDS_GIVEN      15748 non-null  float64
 45  NUMBER_OF_BOD_CHANGES_DURING_FY   15748 non-null  int64
 46  DATE_OF_LAST_BOD_CHANGE           15748 non-null  object
 47  NUM_DIR_INC_IN_CMPNSTN_PD         15748 non-null  int64
dtypes: float64(23), int64(18), object(7)
memory usage: 5.9+ MB



<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 15748 entries, 2014-04-11 to 2023-12-29
Data columns (total 48 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   symbol                            15748 non-null  object
 1   PX_LAST                           15748 non-null  float64
 2   Dividend_Per_Share                15748 non-null  float64
 3   TOTAL_EQUITY                      15748 non-null  float64
 4   CUR_MKT_CAP                       15748 non-null  float64
 5   gics_sector_name                  15748 non-null  object
 6   gics_sub_industry_name            15748 non-null  object
 7   gics_industry_name                15748 non-null  object
 8   gics_industry_group_name          15748 non-null  object
 9   gics_industry                     15748 non-null  int64
 10  gics_sector                       15748 non-null  int64
 11  Year                              15748 non-null  int64
 12  TOT_COMPENSATION_AW_TO_EXECS      15748 non-null  float64
 13  TOT_SALARIES_BNS_PD_TO_EXECS      15748 non-null  float64
 14  TOT_N_EQTY_INCENT_GIVEN_TO_EXECS  15748 non-null  int64
 15  TOT_SALARIES_PAID_TO_EXECUTIVES   15748 non-null  float64
 16  TOTAL_BONUSES_PAID_TO_EXECUTIVES  15748 non-null  int64
 17  ALL_OTHER_COMP_AW_TO_EXECS        15748 non-null  float64
 18  TOT_STK_AWARDS_GIVEN_TO_EXECS     15748 non-null  float64
 19  TOT_OPTION_AWARDS_GIVEN_TO_EXECS  15748 non-null  int64
 20  T_PEN_NQ_DEF_PEN_GVN_TO_EXECS     15748 non-null  float64
 21  TOT_OTHER_COMP_AW_TO_EXECS        15748 non-null  float64
 22  NUM_EXECUTIVE_CHANGES             15748 non-null  int64
 23  DATE_OF_LAST_EXECUTIVE_CHANGE     15748 non-null  datetime64[ns]
 24  NUM_EXECS_INC_IN_COMPENSATION_PD  15748 non-null  int64
 25  CEO_DUALITY                       15748 non-null  int64
 26  TOT_COMP_AW_TO_CEO_EQUIV          15748 non-null  float64
 27  TOT_SAL_BNS_AW_TO_CEO_EQUIV       15748 non-null  float64
 28  TOT_N_EQT_INCENT_GVN_TO_CEO_EQ    15748 non-null  int64
 29  TOT_SALARIES_PAID_TO_CEO_EQUIV    15748 non-null  float64
 30  TOT_BONUSES_PAID_TO_CEO_EQUIV     15748 non-null  int64
 31  ALL_OTHER_COMP_AW_TO_CEO_EQUIV    15748 non-null  float64
 32  TOT_STK_AWD_GIVEN_TO_CEO_EQUIV    15748 non-null  float64
 33  TOT_OPT_AWD_GIVEN_TO_CEO_EQUIV    15748 non-null  int64
 34  T_PEN_NQ_DEF_PEN_GVN_CEO_EQ       15748 non-null  float64
 35  TOT_OTHER_COMP_AW_TO_CEO_EQUIV    15748 non-null  float64
 36  NUM_CEO_EQUIVALENT_CHANGES        15748 non-null  int64
 37  COMP_LKD_LAST_CEO_&_EQUIV_CHG_DT  15748 non-null  int64
 38  NUM_CEOS_EQUIV_INC_COMP_PD        15748 non-null  int64
 39  CEO_TENURE_AS_OF_FY_END           15748 non-null  float64
 40  TOT_COMP_AW_TO_CFO_EQUIV          15748 non-null  float64
 41  TOT_COMP_AW_TO_COO_EQUIV          15748 non-null  int64
 42  TOTAL_BOD_COMPENSATION_AWARDED    15748 non-null  float64
 43  TOTAL_BOD_FEES_PAID_IN_CASH       15748 non-null  float64
 44  TOTAL_BOD_STOCK_AWARDS_GIVEN      15748 non-null  float64
 45  NUMBER_OF_BOD_CHANGES_DURING_FY   15748 non-null  int64
 46  DATE_OF_LAST_BOD_CHANGE           15748 non-null  datetime64[ns]
 47  NUM_DIR_INC_IN_CMPNSTN_PD         15748 non-null  int64
dtypes: datetime64[ns](2), float64(23), int64(18), object(5)
memory usage: 5.9+ MB

DO NOT RUN THIS SECTION MORE THAN ONCE

In [7]:
# One hot encode categorical data; see last .info() call to find desired columns
# 1. symbol
# 2. gics_sector_name
# 3. gics_sub_industry_name
# 4. gics_industry_name
# 5. gics_industry_group_name
# 
# ** gics_industy and gics_sector are already int64
#
# One hot encoding will be done with natively with pandas

ohe_dataframe = date_index_dataframe
display(ohe_dataframe.head())

# columns to one hot encode
# EXCLUDING 'symbol' COLUMN; THE DUMMY VARIABLE DATAFRAME IS BEING INITIALIZED WITH IT 

columns = ['gics_sector_name']
dummy_variables = pd.get_dummies(ohe_dataframe['symbol'])


display(dummy_variables.head())

IndentationError: expected an indented block after 'for' statement on line 21 (927101954.py, line 23)