In [2]:
import os
import pandas as pd
import numpy as np

In [3]:
original_data_import = pd.read_csv('../../data/OriginalData.csv')
dataframe = original_data_import
display(dataframe.head())

,Dates,symbol,PX_LAST,Dividend_Per_Share,TOTAL_EQUITY,CUR_MKT_CAP,gics_sector_name,gics_sub_industry_name,gics_industry_name,gics_industry_group_name,...,NUM_CEOS_EQUIV_INC_COMP_PD,CEO_TENURE_AS_OF_FY_END,TOT_COMP_AW_TO_CFO_EQUIV,TOT_COMP_AW_TO_COO_EQUIV,TOTAL_BOD_COMPENSATION_AWARDED,TOTAL_BOD_FEES_PAID_IN_CASH,TOTAL_BOD_STOCK_AWARDS_GIVEN,NUMBER_OF_BOD_CHANGES_DURING_FY,DATE_OF_LAST_BOD_CHANGE,NUM_DIR_INC_IN_CMPNSTN_PD
0,2014-04-11,AAPL,18.5580,0.1089,120179.000,463486.4114,Information Technology,"Technology Hardware, Storage & Peripherals","Technology Hardware, Storage & Peripherals",Technology Hardware & Equipment,...,1,3.7500,18520521.0,0,2638340.0,697500.0,1906645.0,2,2014-07-17,8
1,2014-04-11,AMT,80.5500,0.3200,3701.605,31870.1921,Real Estate,Telecom Tower REITs,Specialized REITs,Equity Real Estate Investment Trusts (REITs),...,1,11.2500,4904866.0,0,1975088.0,775000.0,600071.0,1,2014-12-18,9
2,2014-04-11,AMZN,15.5870,0.0000,10328.000,143440.4076,Consumer Discretionary,Broadline Retail,Broadline Retail,Consumer Discretionary Distribution & Retail,...,1,18.6670,5962307.0,0,797000.0,0.0,797000.0,1,2014-07-31,9
3,2014-04-11,BHP,58.8727,0.0000,82279.000,180544.3056,Materials,Diversified Metals & Mining,Metals & Mining,Materials,...,1,1.1667,4639000.0,0,4695000.0,3617000.0,0.0,1,2014-04-15,13
4,2014-04-11,CAT,101.4500,0.6000,20369.000,64707.0750,Industrials,Construction Machinery & Heavy Transportation ...,Machinery,Capital Goods,...,1,4.5000,5286968.0,0,3206983.0,1714174.0,1375110.0,1,2014-12-31,11

In [4]:
# Index by Date column, drop Date column as feature 

# First, cast Dates to datetime format
dataframe['Dates'] = pd.to_datetime(dataframe['Dates'])
print(dataframe.info())

double_index_dataframe = dataframe.set_index(['Dates', 'symbol'])
print('\n\n')
display(double_index_dataframe)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15748 entries, 0 to 15747
Data columns (total 49 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Dates                             15748 non-null  datetime64[ns]
 1   symbol                            15748 non-null  object
 2   PX_LAST                           15748 non-null  float64
 3   Dividend_Per_Share                15748 non-null  float64
 4   TOTAL_EQUITY                      15748 non-null  float64
 5   CUR_MKT_CAP                       15748 non-null  float64
 6   gics_sector_name                  15748 non-null  object
 7   gics_sub_industry_name            15748 non-null  object
 8   gics_industry_name                15748 non-null  object
 9   gics_industry_group_name          15748 non-null  object
 10  gics_industry                     15748 non-null  int64
 11  gics_sector                       15748 non-null  int64
 12  Year                              15748 non-null  int64
 13  TOT_COMPENSATION_AW_TO_EXECS      15748 non-null  float64
 14  TOT_SALARIES_BNS_PD_TO_EXECS      15748 non-null  float64
 15  TOT_N_EQTY_INCENT_GIVEN_TO_EXECS  15748 non-null  int64
 16  TOT_SALARIES_PAID_TO_EXECUTIVES   15748 non-null  float64
 17  TOTAL_BONUSES_PAID_TO_EXECUTIVES  15748 non-null  int64
 18  ALL_OTHER_COMP_AW_TO_EXECS        15748 non-null  float64
 19  TOT_STK_AWARDS_GIVEN_TO_EXECS     15748 non-null  float64
 20  TOT_OPTION_AWARDS_GIVEN_TO_EXECS  15748 non-null  int64
 21  T_PEN_NQ_DEF_PEN_GVN_TO_EXECS     15748 non-null  float64
 22  TOT_OTHER_COMP_AW_TO_EXECS        15748 non-null  float64
 23  NUM_EXECUTIVE_CHANGES             15748 non-null  int64
 24  DATE_OF_LAST_EXECUTIVE_CHANGE     15748 non-null  object
 25  NUM_EXECS_INC_IN_COMPENSATION_PD  15748 non-null  int64
 26  CEO_DUALITY                       15748 non-null  int64
 27  TOT_COMP_AW_TO_CEO_EQUIV          15748 non-null  float64
 28  TOT_SAL_BNS_AW_TO_CEO_EQUIV       15748 non-null  float64
 29  TOT_N_EQT_INCENT_GVN_TO_CEO_EQ    15748 non-null  int64
 30  TOT_SALARIES_PAID_TO_CEO_EQUIV    15748 non-null  float64
 31  TOT_BONUSES_PAID_TO_CEO_EQUIV     15748 non-null  int64
 32  ALL_OTHER_COMP_AW_TO_CEO_EQUIV    15748 non-null  float64
 33  TOT_STK_AWD_GIVEN_TO_CEO_EQUIV    15748 non-null  float64
 34  TOT_OPT_AWD_GIVEN_TO_CEO_EQUIV    15748 non-null  int64
 35  T_PEN_NQ_DEF_PEN_GVN_CEO_EQ       15748 non-null  float64
 36  TOT_OTHER_COMP_AW_TO_CEO_EQUIV    15748 non-null  float64
 37  NUM_CEO_EQUIVALENT_CHANGES        15748 non-null  int64
 38  COMP_LKD_LAST_CEO_&_EQUIV_CHG_DT  15748 non-null  int64
 39  NUM_CEOS_EQUIV_INC_COMP_PD        15748 non-null  int64
 40  CEO_TENURE_AS_OF_FY_END           15748 non-null  float64
 41  TOT_COMP_AW_TO_CFO_EQUIV          15748 non-null  float64
 42  TOT_COMP_AW_TO_COO_EQUIV          15748 non-null  int64
 43  TOTAL_BOD_COMPENSATION_AWARDED    15748 non-null  float64
 44  TOTAL_BOD_FEES_PAID_IN_CASH       15748 non-null  float64
 45  TOTAL_BOD_STOCK_AWARDS_GIVEN      15748 non-null  float64
 46  NUMBER_OF_BOD_CHANGES_DURING_FY   15748 non-null  int64
 47  DATE_OF_LAST_BOD_CHANGE           15748 non-null  object
 48  NUM_DIR_INC_IN_CMPNSTN_PD         15748 non-null  int64
dtypes: datetime64[ns](1), float64(23), int64(18), object(7)
memory usage: 5.9+ MB
None

                    PX_LAST  Dividend_Per_Share  TOTAL_EQUITY  CUR_MKT_CAP  \
Dates      symbol
2014-04-11 AAPL     18.5580              0.1089    120179.000  463486.4114
           AMT      80.5500              0.3200      3701.605   31870.1921
           AMZN     15.5870              0.0000     10328.000  143440.4076
           BHP      58.8727              0.0000     82279.000  180544.3056
           CAT     101.4500              0.6000     20369.000   64707.0750
...                     ...                 ...           ...          ...
2023-12-29 UNH     526.4700              1.8800     98919.000  486945.4190
           V       260.3500              0.5200     39733.000  536848.9874
           WFC      49.2200              0.3500    187443.000  178749.3067
           WMT      52.5500              0.1900     85811.000  424430.6433
           XOM      99.9800              0.9500    212538.000  400533.1980

                         gics_sector_name  \
Dates      symbol
2014-04-11 AAPL    Information Technology
           AMT                Real Estate
           AMZN    Consumer Discretionary
           BHP                  Materials
           CAT                Industrials
...                                   ...
2023-12-29 UNH                Health Care
           V                   Financials
           WFC                 Financials
           WMT           Consumer Staples
           XOM                     Energy

                                              gics_sub_industry_name  \
Dates      symbol
2014-04-11 AAPL           Technology Hardware, Storage & Peripherals
           AMT                                   Telecom Tower REITs
           AMZN                                     Broadline Retail
           BHP                           Diversified Metals & Mining
           CAT     Construction Machinery & Heavy Transportation ...
...                                                              ...
2023-12-29 UNH                                   Managed Health Care
           V               Transaction & Payment Processing Services
           WFC                                     Diversified Banks
           WMT                   Consumer Staples Merchandise Retail
           XOM                                  Integrated Oil & Gas

                                           gics_industry_name  \
Dates      symbol
2014-04-11 AAPL    Technology Hardware, Storage & Peripherals
           AMT                              Specialized REITs
           AMZN                              Broadline Retail
           BHP                                Metals & Mining
           CAT                                      Machinery
...                                                       ...
2023-12-29 UNH               Health Care Providers & Services
           V                               Financial Services
           WFC                                          Banks
           WMT         Consumer Staples Distribution & Retail
           XOM                    Oil, Gas & Consumable Fuels

                                       gics_industry_group_name  \
Dates      symbol
2014-04-11 AAPL                 Technology Hardware & Equipment
           AMT     Equity Real Estate Investment Trusts (REITs)
           AMZN    Consumer Discretionary Distribution & Retail
           BHP                                        Materials
           CAT                                    Capital Goods
...                                                         ...
2023-12-29 UNH                 Health Care Equipment & Services
           V                                 Financial Services
           WFC                                            Banks
           WMT           Consumer Staples Distribution & Retail
           XOM                                           Energy

                   gics_industry  gics_sector  ...  \
Dates      symbol                              ...
2014-04-11 AAPL           452020           45  ...
           AMT            601080           60  ...
           AMZN           255030           25  ...
           BHP            151040           15  ...
           CAT            201060           20  ...
...                          ...          ...  ...
2023-12-29 UNH            351020           35  ...
           V              402010           40  ...
           WFC            401010           40  ...
           WMT            301010           30  ...
           XOM            101020           10  ...

                   NUM_CEOS_EQUIV_INC_COMP_PD  CEO_TENURE_AS_OF_FY_END  \
Dates      symbol
2014-04-11 AAPL                             1                   3.7500
           AMT                              1                  11.2500
           AMZN                             1                  18.6670
           BHP                              1                   1.1667
           CAT                              1                   4.5000
...                                       ...                      ...
2023-12-29 UNH                              1                   2.9170
           V                                2                   0.6667
           WFC                              1                   4.2500
           WMT                              2                   9.0000
           XOM                              1                   7.0000

                   TOT_COMP_AW_TO_CFO_EQUIV  TOT_COMP_AW_TO_COO_EQUIV  \
Dates      symbol
2014-04-11 AAPL                  18520521.0                         0
           AMT                    4904866.0                         0
           AMZN                   5962307.0                         0
           BHP                    4639000.0                         0
           CAT                    5286968.0                         0
...                                     ...                       ...
2023-12-29 UNH                   16074137.0                  16074137
           V                     36795259.0                         0
           WFC                   12448986.0                  10395440
           WMT                   41755589.0                         0
           XOM                   18047556.0                         0

                   TOTAL_BOD_COMPENSATION_AWARDED  \
Dates      symbol
2014-04-11 AAPL                         2638340.0
           AMT                          1975088.0
           AMZN                          797000.0
           BHP                          4695000.0
           CAT                          3206983.0
...                                           ...
2023-12-29 UNH                          3389939.0
           V                            4594284.0
           WFC                          4650819.0
           WMT                          3421993.0
           XOM                          5746801.0

                   TOTAL_BOD_FEES_PAID_IN_CASH  TOTAL_BOD_STOCK_AWARDS_GIVEN  \
Dates      symbol
2014-04-11 AAPL                       697500.0                     1906645.0
           AMT                        775000.0                      600071.0
           AMZN                            0.0                      797000.0
           BHP                       3617000.0                           0.0
           CAT                       1714174.0                     1375110.0
...                                        ...                           ...
2023-12-29 UNH                        200000.0                     3071845.0
           V                         1632500.0                     2856784.0
           WFC                       1770639.0                     2880180.0
           WMT                       1306578.0                     2113094.0
           XOM                       1325934.0                     4418160.0

                   NUMBER_OF_BOD_CHANGES_DURING_FY  DATE_OF_LAST_BOD_CHANGE  \
Dates      symbol
2014-04-11 AAPL                                  2               2014-07-17
           AMT                                   1               2014-12-18
           AMZN                                  1               2014-07-31
           BHP                                   1               2014-04-15
           CAT                                   1               2014-12-31
...                                            ...                      ...
2023-12-29 UNH                                   1               2023-10-30
           V                                     4               2023-04-10
           WFC                                   1               2023-04-25
           WMT                                   1               2022-05-31
           XOM                                   3               2023-05-30

                   NUM_DIR_INC_IN_CMPNSTN_PD
Dates      symbol
2014-04-11 AAPL                            8
           AMT                             9
           AMZN                            9
           BHP                            13
           CAT                            11
...                                      ...
2023-12-29 UNH                             9
           V                              12
           WFC                            13
           WMT                            11
           XOM                            12

[15748 rows x 47 columns]

In [60]:
print(double_index_dataframe.index)

MultiIndex([('2014-04-11', 'AAPL'),
            ('2014-04-11',  'AMT'),
            ('2014-04-11', 'AMZN'),
            ('2014-04-11',  'BHP'),
            ('2014-04-11',  'CAT'),
            ('2014-04-11', 'COST'),
            ('2014-04-11',  'CVX'),
            ('2014-04-11',  'DUK'),
            ('2014-04-11', 'EQIX'),
            ('2014-04-11',   'GE'),
            ...
            ('2023-12-29',  'RTX'),
            ('2023-12-29', 'SHEL'),
            ('2023-12-29',  'SHW'),
            ('2023-12-29',   'SO'),
            ('2023-12-29', 'TSLA'),
            ('2023-12-29',  'UNH'),
            ('2023-12-29',    'V'),
            ('2023-12-29',  'WFC'),
            ('2023-12-29',  'WMT'),
            ('2023-12-29',  'XOM')],
           names=['Dates', 'symbol'], length=15748)